### ISSUE TITLE
<Error>Application: DB:: Exception: cnch_ config not found SQLSTATE: F0000

### ISSUE THREAD

**Issue by FourSpaces** [ByConity/byconity-deploy#1]
The configuration of k8s cannot run, the pod is stuck in the update state, and there is an error message<Error>Application: DB:: Exception: cnch_ config not found SQLSTATE: F0000

**Comment by dmthuc** [comment]
Hi @zhuminjie-byted please take a look

**Comment by FourSpaces** [comment]
#7  This issue has been fixed here
