### ISSUE TITLE
ERROR: failed to create cluster

### ISSUE THREAD

**Issue by vinijaiswal** [ByConity/byconity-deploy#14]
I am following the docker-deploy guide and keep running into errors at the [docker step](https://byconity.github.io/docs/deployment/deploy-k8s#use-kind-to-configure-a-local-kubernetes-cluster)

I checked to make sure that I have installed all the prerequisite components including docker, helm, kind and kubectl.

**Following is the error I get:**
```
byconity-deploy bytedance$ kind create cluster --config examples/kind/kind-byconity.yaml
ERROR: failed to create cluster: failed to list nodes: command "docker ps -a --filter label=io.x-k8s.kind.cluster=byconity-cluster --format '{{.Names}}'" failed with error: exit status 1
Command Output: Cannot connect to the Docker daemon at unix:///Users/bytedance/.colima/default/docker.sock. Is the docker daemon running?
```

**Comment by dmthuc** [comment]
Hi @weigangchen1 , please help to take a look at this issue

**Comment by weigangchen1** [comment]
> I am following the docker-deploy guide and keep running into errors at the [docker step](https://byconity.github.io/docs/deployment/deploy-k8s#use-kind-to-configure-a-local-kubernetes-cluster)
> 
> I checked to make sure that I have installed all the prerequisite components including docker, helm, kind and kubectl.
> 
> **Following is the error I get:**
> 
> ```
> byconity-deploy bytedance$ kind create cluster --config examples/kind/kind-byconity.yaml
> ERROR: failed to create cluster: failed to list nodes: command "docker ps -a --filter label=io.x-k8s.kind.cluster=byconity-cluster --format '{{.Names}}'" failed with error: exit status 1
> Command Output: Cannot connect to the Docker daemon at unix:///Users/bytedance/.colima/default/docker.sock. Is the docker daemon running?
> ```

Can you confirm that your docker process has started?

**Comment by dmthuc** [comment]
Hi @vinijaiswal , i think we can check if your docker process has started with `sudo systemctl status docker`. For me the output is like this
![image](https://github.com/ByConity/byconity-deploy/assets/13962605/597f77be-18eb-4758-b75b-0e692d565ac8)
