### ISSUE TITLE
There are two ‘hdfs3Config’ configuration in the 'values. yaml' file, should be merged into one

### ISSUE THREAD

**Issue by FourSpaces** [ByConity/byconity-deploy#17]
There are two ‘hdfs3Config’ configuration in the 'values. yaml' file, should be merged into one.

Two identical configurations can result in inconsistencies when modifying.

**Comment by dmthuc** [comment]
Hi @FourSpaces , thank you for your comment. We should fix this, could you help us to fix this, the correct hdfs3Config final position should be in cnch_config.xml in final deployment. Could you help us to fix this?

**Comment by FourSpaces** [comment]
@dmthuc Okay, I'll do it this week

**Comment by FourSpaces** [comment]
@dmthuc  Ok, I will solve this problem

**Comment by FourSpaces** [comment]
@dmthuc  I see that the parameter 'hdfs_ha_nameservice' cannot be configured. It should also be added so that it can be used for production of HDFS

**Comment by dmthuc** [comment]
> @dmthuc I see that the parameter 'hdfs_ha_nameservice' cannot be configured. It should also be added so that it can be used for production of HDFS

Yeah, what do you think @weigangchen1 ?

**Comment by FourSpaces** [comment]
@dmthuc  I plan to add a judgment in the configuration to add this feature

It should look like this

![image](https://github.com/ByConity/byconity-deploy/assets/13359726/750d8ea2-121f-4693-8e71-59392ddcc6d8)

**Comment by FourSpaces** [comment]
I plan to add 'hdfs3Config' under 'byconsistency. configOverwrite'. What do you think 。

It looks like this：
![image](https://github.com/ByConity/byconity-deploy/assets/13359726/df9e0ff2-1bd5-48ee-8cb9-dee3dea68baa)

**Comment by dmthuc** [comment]
> 

yeah, this is look good to me

**Comment by FourSpaces** [comment]
@dmthuc   I saw that 'hdfs3Config' is used in the 'hdfs3. xml' file instead of the 'cnch config. yaml' file, so I moved hdfs3Config to the '.byconity' node here.

![image](https://github.com/ByConity/byconity-deploy/assets/13359726/b977c611-4084-419a-9d4b-c628652fb972)

**Comment by FourSpaces** [comment]
@dmthuc  I have added these two functions. Please check if there are any problems.
