### ISSUE TITLE
Just run ByConity on k8s

### ISSUE THREAD

**Issue by FourSpaces** [ByConity/byconity-deploy#2]
We want to only run ByConity on k8s. How do we configure FDB and HDFS to use existing services

**Comment by dmthuc** [comment]
Hi @FourSpaces , thank you for try ByConity. You can refer to this document https://github.com/ByConity/ByConity/blob/master/packages/config_service_discovery.md on that

**Comment by dmthuc** [comment]
Basically, you need to edit config file cnch_config.xml and it will do.

**Comment by FourSpaces** [comment]
@dmthuc  We want to use ByConity's chart to install ByConity, but the chart contains both Hdfs and fdb components. We want a chart that only contains ByConity components.
